apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dowk-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/jeknom/dev-ops-with-kubernetes-2022
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todo-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: dowk-repo
  interval: 1m
  path: ./part4/4-08-project-v2.1
  prune: true
  validation: client